[theme]
base                = "dark"
primaryColor        = "#ab99d0f0"
backgroundColor     = "#64759bff"
secondaryBackgroundColor = "#1E293B"
textColor           = "#040a11ff"
font                = "monospace"

[server]
maxUploadSize       = 200
enableCORS          = false
enableXsrfProtection = true

[browser]
gatherUsageStats    = false
